In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [3]:
training_inputs=np.array([[0,0,1],
                          [1,1,1],
                          [1,0,1],
                          [0,1,1]])

In [4]:
training_outputs=np.array([[0,1,1,0]]).T

In [5]:
np.random.seed(1)

In [6]:
synaptic_weights=2*np.random.random((3,1))-1

In [7]:
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [10]:
for iteration in range(1):
    #input_layer=training_inputs
    outputs=sigmoid(np.dot(training_inputs,synaptic_weights))
print('Outputs after training:')
print (outputs)

Outputs after training:
[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]


In [11]:
#Output is erronous

In [12]:
# so regulisation is done
def sigmoid_derivative(x):
    return x*(1-x)

In [14]:
#Updated for loop

for iteration in range(2000):
    #input_layer=training_inputs
    outputs=sigmoid(np.dot(training_inputs,synaptic_weights))
    error=training_outputs-outputs
    adjustments=error*sigmoid_derivative(outputs)
    synaptic_weights+=np.dot(input_layer.T,adjustments)
print('Synaptic wt.s after training:')
print (synaptic_weights)
print('Output after training:')
print(outputs)

Synaptic wt.s after training:
[[ 8.72812088]
 [-0.21048991]
 [-4.15496406]]
Output after training:
[[0.01544608]
 [0.9874144 ]
 [0.9897789 ]
 [0.012551  ]]
